from analyzer import (
    calculate_basic_stats,
    find_best_subject,
    find_best_period,
    find_most_distracting_subject,
    find_best_session_length,
    calculate_consistency
)


REPORT_PATH = "reports/focus_report.txt"


def generate_report(sessions):
    if not sessions:
        return "No study data available for report."

    stats = calculate_basic_stats(sessions)
    best_subject = find_best_subject(sessions)
    best_period = find_best_period(sessions)
    distracting_subject = find_most_distracting_subject(sessions)
    best_session_length = find_best_session_length(sessions)
    consistency = calculate_consistency(sessions)

    report = f"""========================================
          FOCUSFINGERPRINT REPORT
========================================

PERSONAL STUDY PATTERN ANALYSIS

----------------------------------------
BASIC STATISTICS
----------------------------------------

Total Study Time       : {stats['total_duration']} minutes
Average Focus          : {stats['average_focus']}/5
Average Distractions   : {stats['average_distractions']}

----------------------------------------
STUDY PATTERN
----------------------------------------

Best Subject for Focus : {best_subject}
Best Study Period      : {best_period}
Best Session Length    : {best_session_length}
Most Distracting Area  : {distracting_subject}
Study Consistency      : {consistency}%

----------------------------------------
FOCUSFINGERPRINT
----------------------------------------

Strongest Subject      : {best_subject}
Preferred Study Period : {best_period}
Ideal Session Length   : {best_session_length}
Main Distraction Area  : {distracting_subject}
Average Focus          : {stats['average_focus']}/5

----------------------------------------
SUMMARY
----------------------------------------

Your recorded study sessions were analyzed
to identify your personal study patterns.

The fingerprint is based on subject,
study period, session length, focus rating,
distractions and consistency.

========================================
Generated by FocusFingerprint
========================================
"""

    with open(REPORT_PATH, "w") as file:
        file.write(report)

    return report